% examples.m
% Various examples of using the flypath3d package

% Example A: Ballistic missile flight trajectory
trajectory = load('trajectory_tbm.mat');
new_object('ballistic_missile.mat', trajectory, ...
    'model', 'scud.mat', 'scale', 800, ...
    'edge', [0 0 0], 'face', [0 0 0], 'alpha', 1, ...
    'path', 'on', 'pathcolor', [.89 .0 .27], 'pathwidth', 1);
flypath('ballistic_missile.mat', ...
    'animate', 'off', 'step', 30, ...
    'axis', 'on', 'axiscolor', [0 0 0], 'color', [1 1 1], ...
    'font', 'Georgia', 'fontsize', 6, ...
    'view', [0 0], 'window', [1800 600], ...
    'xlim', [-2e4 16e4], 'ylim', [-10 10], 'zlim', [0 4e4], ...
    'output', 'tbm_example.png', 'dpi', 600);

% Example B: Air target trajectory
trajectory = load('trajectory_aircraft.mat');
new_object('aircraft.mat', trajectory, ...
    'model', 'f-16.mat', 'scale', 100, ...
    'edge', [0 0 0], 'face', [0 0 0], 'alpha', 1, ...
    'path', 'on', 'pathcolor', [.89 .0 .27], 'pathwidth', 1);
flypath('aircraft.mat', ...
    'animate', 'off', 'step', 150, ...
    'axis', 'on', 'axiscolor', [0 0 0], 'color', [1 1 1], ...
    'font', 'Georgia', 'fontsize', 6, ...
    'view', [0 90], 'window', [1800 900], ...
    'xlim', [-15e3 10e3], 'ylim', [-5e3 25e3], 'zlim', [-15e3 15e3], ...
    'output', 'aircraft_example.png', 'dpi', 600);

% Example C: Visualization of missile airframe stability
load('airframe_stabilized.mat');
new_object('missile_ap.mat', data, ...
    'model', 'missile.mat', 'scale', 1, ...
    'edge', 'none', 'face', [0 0 0], 'alpha', .6, ...
    'path', 'off');
load('airframe_nonstabilized.mat');
new_object('missile_nonap.mat', data, ...
    'model', 'missile.mat', 'scale', 1, ...
    'edge', 'none', 'face', [.89 .0 .27], 'alpha', .6, ...
    'path', 'off');
flypath('missile_ap.mat', 'missile_nonap.mat', ...
    'xlim', [-1.5 1.5], 'ylim', [-2.0 2.0], 'zlim', [-1.5 1.5], ...
    'font', 'Georgia', 'fontsize', 12, ...
    'view', [0 90], 'animate', 'on', 'step', 200);

% Example D: Target-missile engagement visualization
load('trajectory_enemy.mat');
new_object('enemy.mat', data, ...
    'model', 'f-16.mat', 'edge', [.2 .2 .2], 'face', [.3 .3 .3], ...
    'path', 'on', 'pathcolor', [.3 .3 .3], 'pathwidth', 1, 'scale', 10.0);
load('trajectory_friend.mat');
new_object('friend.mat', data, ...
    'model', 'f-16.mat', 'edge', [.2 .2 .2], 'face', [.3 .3 .3], ...
    'path', 'on', 'pathcolor', [.89 .27 .0], 'pathwidth', 1, 'scale', 10.0);
load('trajectory_aam.mat');
new_object('aam.mat', data, ...
    'model', 'missile.mat', 'edge', [.2 .2 .2], 'face', [.3 .3 .3], ...
    'path', 'on', 'pathcolor', [.89 .47 .0], 'pathwidth', 1, 'scale', 10.0);
flypath('friend.mat', 'enemy.mat', 'aam.mat', ...
    'animate', 'off', 'step', 9000, ...
    'font', 'Georgia', 'fontsize', 6, ...
    'view', [-90 90], 'window', [1000 280], ...
    'output', 'combat_example.png', 'dpi', 600, ...
    'xlim', [-500 500], 'ylim', [-500 3500], 'zlim', [500 1500]);

% Additional examples...
